global:
    scrape_interval: 15s     # Set the scrape interval to every 15 seconds. Default is every 1 minute.
    evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
    scrape_timeout: 10s      # is set to the global default (10s).

scrape_configs:
  - job_name: "node-exporter"
    static_configs:
      - targets:
          - ec2-3-73-74-78.eu-central-1.compute.amazonaws.com:9100
        labels:
          environment: monitoring
      - targets:
          - ec2-18-185-220-1.eu-central-1.compute.amazonaws.com:9100
          - ec2-3-74-222-225.eu-central-1.compute.amazonaws.com:9100
        labels:
          environment: jenkins
      - targets:
          - ec2-3-70-8-77.eu-central-1.compute.amazonaws.com:9100
        labels:
          environment: kubernetes
