version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    volumes:
      - ./jobs:/var/jenkins_home/jobs:rw
      - jenkins:/var/jenkins_home:rw
    ports:
      - "8080:8080"
      - "5000:5000"

volumes:
  jenkins:
