---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: abc-technologies-deployment
  labels:
    app: abc-technologies
spec:
  replicas: 1
  selector:
    matchLabels:
      app: abc-technologies
  template:
    metadata:
      labels:
        app: abc-technologies
    spec:
      containers:
      - name: abc-technologies
        image: guilhermesfl/abc-technologies-retail:latest
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: abc-technologies-service
spec:
  type: LoadBalancer
  selector:
    app: abc-technologies
  ports:
  # Default port used by the image
  - port: 8080
